name: "vuepress-build"

on:
  push:
    branches: [master]

env:
  EXCLUDE_WEB_PAGES: "(mylabs.dev|localhost)"

jobs:
  terraform-checks:
    name: "Terraform checks"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Terraform"
      run: |
        export TERRAFORM_LATEST_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
        curl --silent --location https://releases.hashicorp.com/terraform/${TERRAFORM_LATEST_VERSION}/terraform_${TERRAFORM_LATEST_VERSION}_linux_amd64.zip --output /tmp/terraform_linux_amd64.zip
        sudo unzip -q -o /tmp/terraform_linux_amd64.zip -d /usr/local/bin/

    - name: "Generate ssh key if needed"
      run: |
        install -m 0700 -d $HOME/.ssh
        ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -q -N ""

    - name: "Fill terraform variables with test data"
      run: |
        cat > terraform.tfvars << EOF
        openstack_instance_image_name  = "test"
        openstack_password             = "test"
        openstack_tenant_name          = "test"
        openstack_user_domain_name     = "test"
        openstack_user_name            = "test"
        openstack_auth_url             = "test"
        openstack_instance_flavor_name = "test"
        EOF

    - name: "Run terraform checks"
      run: |
        terraform init     -var-file=terraform.tfvars terrafrom/openstack
        terraform validate -var-file=terraform.tfvars terrafrom/openstack

  command-check:
    name: "Command check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Update repositories"
      run: sudo apt update

    - name: "Run tests"
      run: |
        sudo apt install -y pv siege
        tests/ci_test.sh

  markdown-lint-check:
    name: "Markdown lint check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install markdownlint-cli"
      run: npm install -g markdownlint-cli

    - name: "Create markdownlint configuration file"
      run: |
        echo "{ MD013: { code_blocks: false } }" > /tmp/markdownlint_config.json

    - name: "Run markdownlint"
      run: find . -path ./node_modules -prune -o -name "*.md" -print0 | xargs -t -0 markdownlint -c /tmp/markdownlint_config.json

  markdown-spell-check:
    name: "Markdown spell check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install markdown-spellcheck"
      run: npm install -g markdown-spellcheck

    - name: "Run mdspell"
      run: mdspell '**/*.md' '!**/node_modules/**/*.md' --ignore-numbers --ignore-acronyms --report --en-gb

  vuepress-build:
    name: "VuePress build"
    runs-on: ubuntu-18.04
    needs:
      - markdown-lint-check
      - markdown-spell-check

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install VuePress and build the document"
      run: |
        npm install
        npm run build
        cp LICENSE docs/.vuepress/dist
        ln -s docs/.vuepress/dist ${GITHUB_REPOSITORY##*/}
        sed -e "s@(lab-@(https://github.com/${GITHUB_REPOSITORY}/tree/master/docs/lab-@" -e 's@.\/.vuepress\/public\/@./@' docs/README.md > docs/.vuepress/dist/README.md

    - name: "Check links"
      run: |
        echo "127.0.0.1 ${GITHUB_REPOSITORY%/*}.github.io" | sudo tee -a /etc/hosts
        curl -s https://getcaddy.com | bash -s personal
        cat > Caddyfile << EOF
        https://${GITHUB_REPOSITORY%/*}.github.io
        tls self_signed
        EOF
        sudo caddy -quiet &
        go get -u github.com/raviqqe/muffet
        ~/go/bin/muffet --concurrency=10 --skip-tls-verification --exclude "${EXCLUDE_WEB_PAGES}" https://${GITHUB_REPOSITORY%/*}.github.io/${GITHUB_REPOSITORY##*/}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/.vuepress/dist
      with:
        emptyCommits: false
        forceOrphan: true
